/* Colorful runtime - the complete C ABI used by code generated from .cf files.
 *
 * Design rules (see docs/spec.md):
 *   - no interpreter, no bytecode VM, no eval, no AST walking
 *   - no garbage collector by default: containers and strings come from a
 *     region/arena allocator that is released when the program exits
 *   - exceptions are propagated by the *compiler* through explicit error tests
 *     on `cf_err_pending()`; the runtime only records the pending exception
 *   - all values are statically typed in the generated code; the tags below are
 *     only used so that a single container implementation can serve every
 *     instantiated type (monomorphized wrappers are generated by the compiler)
 */
#ifndef COLORFUL_RUNTIME_H
#define COLORFUL_RUNTIME_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The runtime is shipped both as a static Colorful Library (libcolorful.cl) and
 * as a shared runtime (colorful.dll). Symbols are exported only in the DLL
 * build; a static link therefore does not decorate (or re-export) anything. */
#if defined(_WIN32)
#if defined(CF_BUILD_DLL)
#define CF_EXPORT __declspec(dllexport)
#elif defined(CF_USE_DLL)
#define CF_EXPORT __declspec(dllimport)
#else
#define CF_EXPORT
#endif
#elif defined(CF_BUILD_DLL)
#define CF_EXPORT __attribute__((visibility("default")))
#else
#define CF_EXPORT
#endif

/* --------------------------------------------------------------- kinds --- */
typedef enum {
  CF_K_NIL = 0,
  CF_K_INT = 1,
  CF_K_FLOAT = 2,
  CF_K_BOOL = 3,
  CF_K_STR = 4,
  CF_K_LIST = 5,
  CF_K_DICT = 6,
  CF_K_RECORD = 7,
  CF_K_FUNC = 8
} cf_kind;

/* --------------------------------------------------------------- values -- */
typedef struct cf_str {
  int64_t len;
  int64_t cap;
  char* data; /* always NUL terminated */
} cf_str;

typedef struct cf_list {
  int64_t len;
  int64_t cap;
  int64_t elemSize;
  int32_t kind; /* element kind, for printing and sorting */
  int32_t pad;
  char* data;
} cf_list;

typedef struct cf_dict {
  int64_t len;
  int64_t cap;
  int64_t valSize;
  int32_t keyKind;
  int32_t valKind;
  void* entries; /* cf_dict_entry* */
} cf_dict;

typedef struct cf_dict_entry {
  cf_str* kstr;
  int64_t kint;
  char* val;
  int32_t used;
  int32_t pad;
} cf_dict_entry;

typedef struct cf_exc {
  cf_str* kind;
  cf_str* message;
  int64_t code;
} cf_exc;

typedef struct cf_closure {
  void* fn;
  void* env;
} cf_closure;

/* A boxed protocol value: the object plus the vtable of the concrete record. */
typedef struct cf_proto {
  void* obj;
  void* vt;
} cf_proto;

/* Eager future used by async functions (v0.1 semantics - see docs/spec.md). */
typedef struct cf_future {
  int32_t state; /* 0 = pending, 1 = ready, 2 = failed */
  int32_t pad;
  void* value;
} cf_future;

/* ------------------------------------------------------------- lifecycle - */
CF_EXPORT void cf_rt_init(void);
CF_EXPORT void cf_rt_shutdown(int64_t status);
CF_EXPORT void cf_rt_set_args(int argc, char** argv);
CF_EXPORT int64_t cf_rt_arg_count(void);
CF_EXPORT cf_str* cf_rt_arg(int64_t i);
CF_EXPORT void* cf_arena_alloc(int64_t size);
CF_EXPORT int64_t cf_arena_bytes(void);

/* --------------------------------------------------------------- strings - */
CF_EXPORT cf_str* cf_str_new(const char* data, int64_t len);
CF_EXPORT cf_str* cf_str_lit(const char* cstr, int64_t len);
CF_EXPORT const char* cf_str_cstr(cf_str* s);
CF_EXPORT int64_t cf_str_len(cf_str* s);
CF_EXPORT cf_str* cf_str_concat(cf_str* a, cf_str* b);
CF_EXPORT cf_str* cf_str_at(cf_str* s, int64_t i); /* one character, throws */
CF_EXPORT cf_str* cf_str_upper(cf_str* s);
CF_EXPORT cf_str* cf_str_lower(cf_str* s);
CF_EXPORT cf_str* cf_str_strip(cf_str* s);
CF_EXPORT cf_list* cf_str_split(cf_str* s, cf_str* sep);
CF_EXPORT cf_str* cf_str_join(cf_str* sep, cf_list* parts);
CF_EXPORT cf_str* cf_str_replace(cf_str* s, cf_str* from, cf_str* to);
CF_EXPORT int cf_str_startswith(cf_str* s, cf_str* prefix);
CF_EXPORT int cf_str_endswith(cf_str* s, cf_str* suffix);
CF_EXPORT int cf_str_contains(cf_str* s, cf_str* needle);
CF_EXPORT int64_t cf_str_find(cf_str* s, cf_str* needle, int64_t from);
CF_EXPORT int cf_str_eq(cf_str* a, cf_str* b);
CF_EXPORT int cf_str_cmp(cf_str* a, cf_str* b);
CF_EXPORT cf_str* cf_str_slice(cf_str* s, int64_t from, int64_t to);
CF_EXPORT cf_str* cf_str_chr(int64_t codePoint); /* UTF-8 encode one code point */
CF_EXPORT int64_t cf_str_ord(cf_str* s, int64_t i); /* UTF-8 decode byte i, throws */

/* --------------------------------------------------------------- output -- */
CF_EXPORT void cf_print_str(cf_str* s);
CF_EXPORT void cf_print_int(int64_t v);
CF_EXPORT void cf_print_float(double v);
CF_EXPORT void cf_print_bool(int64_t v);
CF_EXPORT void cf_print_nil(void);
CF_EXPORT void cf_print_sep(void);
CF_EXPORT void cf_print_nl(void);
CF_EXPORT void cf_print_flush(void);
CF_EXPORT void cf_print_list(cf_list* l);
CF_EXPORT void cf_print_dict(cf_dict* d);
CF_EXPORT void cf_print_rec_start(const char* typeName);
CF_EXPORT void cf_print_rec_field(const char* name);
CF_EXPORT void cf_print_rec_field_str(const char* name, cf_str* v);
CF_EXPORT void cf_print_rec_field_int(const char* name, int64_t v);
CF_EXPORT void cf_print_rec_field_float(const char* name, double v);
CF_EXPORT void cf_print_rec_field_bool(const char* name, int64_t v);
CF_EXPORT void cf_print_rec_field_nil(const char* name);
CF_EXPORT void cf_print_rec_end(void);

/* ---------------------------------------------------------- conversions -- */
CF_EXPORT cf_str* cf_str_from_int(int64_t v);
CF_EXPORT cf_str* cf_str_from_float(double v);
CF_EXPORT cf_str* cf_str_from_bool(int64_t v);
CF_EXPORT int64_t cf_int_from_str(cf_str* s);   /* throws on bad input */
CF_EXPORT double cf_float_from_str(cf_str* s);  /* throws on bad input */
CF_EXPORT int64_t cf_bool_from_int(int64_t v);
CF_EXPORT int64_t cf_int_from_float(double v);

/* checked arithmetic: reports division by zero through the error flag */
CF_EXPORT int64_t cf_div_int(int64_t a, int64_t b);
CF_EXPORT int64_t cf_mod_int(int64_t a, int64_t b);
CF_EXPORT double cf_div_float(double a, double b);

/* -------------------------------------------------------------- lists ---- */
CF_EXPORT cf_list* cf_list_new(int64_t elemSize, int32_t kind);
CF_EXPORT void cf_list_push(cf_list* l, const void* elem);
CF_EXPORT void* cf_list_at(cf_list* l, int64_t i); /* throws when out of range */
CF_EXPORT void cf_list_set(cf_list* l, int64_t i, const void* elem);
CF_EXPORT void cf_list_insert(cf_list* l, int64_t i, const void* elem);
CF_EXPORT void cf_list_remove_at(cf_list* l, int64_t i);
CF_EXPORT void cf_list_clear(cf_list* l);
CF_EXPORT void cf_list_sort(cf_list* l);
CF_EXPORT void cf_list_reverse(cf_list* l);
CF_EXPORT int64_t cf_list_index(cf_list* l, const void* elem); /* -1 when absent */
CF_EXPORT int cf_list_contains(cf_list* l, const void* elem);
CF_EXPORT cf_list* cf_list_copy(cf_list* l);

/* -------------------------------------------------------------- dicts ---- */
CF_EXPORT cf_dict* cf_dict_new(int32_t keyKind, int32_t valKind, int64_t valSize);
CF_EXPORT void cf_dict_set(cf_dict* d, const void* key, const void* val);
CF_EXPORT void* cf_dict_get(cf_dict* d, const void* key); /* throws when missing */
CF_EXPORT int cf_dict_has(cf_dict* d, const void* key);
CF_EXPORT void cf_dict_remove(cf_dict* d, const void* key);
CF_EXPORT cf_list* cf_dict_keys(cf_dict* d);
CF_EXPORT cf_list* cf_dict_values(cf_dict* d);
CF_EXPORT void cf_dict_clear(cf_dict* d);

/* ------------------------------------------------------------- errors ---- */
CF_EXPORT void cf_throw(cf_str* kind, cf_str* msg);
CF_EXPORT void cf_throw_c(const char* kind, const char* msg);
CF_EXPORT void cf_rethrow(cf_exc* e);
CF_EXPORT cf_exc* cf_err_take(void);
CF_EXPORT cf_exc* cf_err_peek(void);
CF_EXPORT int cf_err_pending(void);
CF_EXPORT void cf_err_clear(void);
CF_EXPORT void cf_err_uncaught(void); /* prints the pending exception and exits */
CF_EXPORT cf_str* cf_exc_kind(cf_exc* e);
CF_EXPORT cf_str* cf_exc_message(cf_exc* e);
CF_EXPORT int64_t cf_exc_code(cf_exc* e);
/* Used by the compiler to test an exception kind in an `except` clause. */
CF_EXPORT int cf_exc_is(const char* kind);

/* --------------------------------------------------------------- math ---- */
CF_EXPORT double cf_math_sqrt(double v);
CF_EXPORT double cf_math_sin(double v);
CF_EXPORT double cf_math_cos(double v);
CF_EXPORT double cf_math_tan(double v);
CF_EXPORT double cf_math_log(double v);
CF_EXPORT double cf_math_log10(double v);
CF_EXPORT double cf_math_pow(double a, double b);
CF_EXPORT int64_t cf_math_ipow(int64_t a, int64_t b);
CF_EXPORT double cf_math_floor(double v);
CF_EXPORT double cf_math_ceil(double v);
CF_EXPORT double cf_math_round(double v);
CF_EXPORT double cf_math_absf(double v);
CF_EXPORT int64_t cf_math_absi(int64_t v);
CF_EXPORT double cf_math_pi(void);
CF_EXPORT double cf_math_e(void);

/* ------------------------------------------------------------ io / fs ---- */
CF_EXPORT cf_str* cf_io_read(cf_str* path);                 /* throws */
CF_EXPORT int64_t cf_io_write(cf_str* path, cf_str* data);  /* throws */
CF_EXPORT int64_t cf_io_append(cf_str* path, cf_str* data); /* throws */
CF_EXPORT int64_t cf_io_print(cf_str* text);
CF_EXPORT cf_str* cf_io_read_line(void);
CF_EXPORT int64_t cf_fs_exists(cf_str* path);
CF_EXPORT cf_list* cf_fs_list_dir(cf_str* path); /* throws */
CF_EXPORT int64_t cf_fs_remove(cf_str* path);    /* throws */
CF_EXPORT int64_t cf_fs_mkdir(cf_str* path);
CF_EXPORT cf_str* cf_fs_cwd(void); /* "" when the OS refuses */

/* ---------------------------------------------------------- environment ---- */
CF_EXPORT cf_str* cf_env_get(cf_str* key);                /* "" when unset */
CF_EXPORT int64_t cf_env_has(cf_str* key);
CF_EXPORT int64_t cf_env_set(cf_str* key, cf_str* value); /* 1 on success */

/* --------------------------------------------------------------- time ---- */
CF_EXPORT double cf_time_now(void);
CF_EXPORT int64_t cf_time_millis(void);
CF_EXPORT void cf_time_sleep(int64_t millis);
CF_EXPORT cf_str* cf_time_format(double seconds, cf_str* fmt);

/* ----------------------------------------------------------- random ------ */
CF_EXPORT void cf_random_seed(int64_t seed);
CF_EXPORT int64_t cf_random_int(int64_t lo, int64_t hi);
CF_EXPORT double cf_random_float(void);

/* -------------------------------------------------------------- net ------ */
CF_EXPORT int64_t cf_net_listen(int64_t port);            /* throws */
CF_EXPORT int64_t cf_net_connect(cf_str* host, int64_t port); /* throws */
CF_EXPORT int64_t cf_net_accept(int64_t fd);              /* throws */
CF_EXPORT cf_str* cf_net_recv(int64_t fd, int64_t maxBytes);
CF_EXPORT int64_t cf_net_send(int64_t fd, cf_str* data);
CF_EXPORT void cf_net_close(int64_t fd);

/* --------------------------------------------------------------- tests --- */
CF_EXPORT void cf_test_begin(cf_str* name);
CF_EXPORT void cf_test_ok(int64_t cond, cf_str* what);
CF_EXPORT int64_t cf_test_failures(void);

#ifdef __cplusplus
}
#endif
#endif /* COLORFUL_RUNTIME_H */
